num_sectors: 1000215216
sector_size: 512

sudo ADDITIONAL_DTB_OVERLAY_OPT="BootOrderNvme.dtbo" ./tools/kernel_flash/l4t_initrd_flash.sh \
--external-device nvme0n1p1 \
-c tools/kernel_flash/flash_l4t_external.xml \
-p "-c bootloader/t186ref/cfg/flash_l4t_t194_spi_emmc_p3668.xml --no-systemimg" \
--showlogs --network usb0 jetson-xavier-nx-devkit-emmc external


Worked but boot failed with "can't find PARTUUID=xxxxx":

sudo ADDITIONAL_DTB_OVERLAY_OPT="BootOrderNvme.dtbo" \
./tools/kernel_flash/l4t_initrd_flash.sh \
--external-device nvme0n1p1 \
-c tools/kernel_flash/flash_l4t_external.xml \
-p "-c bootloader/t186ref/cfg/flash_l4t_t194_spi_emmc_p3668.xml --no-systemimg" \
-S 450GiB \
--showlogs --network usb0 \
 jetson-xavier-nx-devkit-emmc external


Worked! boot successful, only 15GB of 500GB nvme used for root:

sudo ADDITIONAL_DTB_OVERLAY_OPT="BootOrderNvme.dtbo" \
./tools/kernel_flash/l4t_initrd_flash.sh \
--external-device nvme0n1p1 \
-c tools/kernel_flash/flash_l4t_nvme.xml \
-p "-c bootloader/t186ref/cfg/flash_l4t_t194_spi_emmc_p3668.xml" \
--showlogs --network usb0 \
jetson-xavier-nx-devkit-emmc nvme0n1p1


Do not work. looks for mmcblk0p1 instead of nvme0n1p1:
sudo ADDITIONAL_DTB_OVERLAY_OPT="BootOrderNvme.dtbo" \
./tools/kernel_flash/l4t_initrd_flash.sh \
--external-device nvme0n1p1 \
-c tools/kernel_flash/flash_l4t_nvme.xml \
-p "-c bootloader/t186ref/cfg/flash_l4t_t194_spi_emmc_p3668.xml --no-systemimg" \
-S 450GiB \
--showlogs --network usb0 \
jetson-xavier-nx-devkit-qspi nvme0n1p1

Working Final!:

sudo ADDITIONAL_DTB_OVERLAY_OPT="BootOrderNvme.dtbo" \
./tools/kernel_flash/l4t_initrd_flash.sh \
--external-device nvme0n1p1 \
-c tools/kernel_flash/flash_l4t_nvme.xml \
-p "-c bootloader/t186ref/cfg/flash_l4t_t194_spi_emmc_p3668.xml --no-systemimg" \
-S 450GiB \
--showlogs --network usb0 \
jetson-xavier-nx-devkit-emmc nvme0n1p1
